import streamlit as st
from PIL import Image

st.set_page_config(
    page_title="Arctic",
    page_icon="🌩",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title('👋 :orange[Hello]')



st.markdown('This website displays the **lightning NO$_2$** products observed by **TROPOMI** in the **Arctic**.')
st.markdown('The original NetCDF products are generated by [S5P-LNO2](https://github.com/zxdawn/S5P-LNO2) \
using TROPOMI NO$_2$ [PAL](https://data-portal.s5p-pal.com/) L2 data and \
[VAISALA GLD360](https://www.vaisala.com/en/products/systems/lightning/gld360) data.')
st.markdown('These data are processed and regridded to a NetCDF product of 0.1 $\\times$ 0.1 degrees, \
    making them more accessible for viewing and analysis.')
st.markdown('Please feel free to explore the interactive images shown in ??? page.')

image = Image.open('homepage.jpg')

st.image(image)