import streamlit as st
from PIL import Image

st.set_page_config(
    page_title="Arctic",
    page_icon="🌩",
    layout="wide",
    initial_sidebar_state="expanded",
)

# decrease pad to page top
st.write('<style>div.block-container{padding-top:2rem;}</style>', unsafe_allow_html=True)

# set title
st.title('👋 :orange[Hello]')

st.markdown('### Introduction')
st.markdown('The Arctic region is experiencing notable warming as well as increasing lightning. \
            Lightning is the dominant source of upper tropospheric nitrogen oxides (NO$_x$), \
            which are a precursor for ozone and hydroxyl radicals.')
st.markdown('This website displays the **lightning NO$_2$** products observed by **TROPOMI** in the **Arctic**. \
             The original NetCDF products are generated by [S5P-LNO2](https://github.com/zxdawn/S5P-LNO2) \
                using TROPOMI NO$_2$ [PAL](https://data-portal.s5p-pal.com/) L2 data and \
                [VAISALA GLD360](https://www.vaisala.com/en/products/systems/lightning/gld360) data. \
             These data are processed and regridded to a NetCDF product of 0.1 $\\times$ 0.1 degrees, \
                making them more accessible for viewing and analysis.')
st.markdown('Please feel free to explore the interactive images in the **🛰 Quickview page** (on the left slidebar).')
            #  <a href="https://arctic-lightning-no2.streamlit.app/Quickview" target="_self">Quickview</a> page.', unsafe_allow_html=True)

st.markdown('### Want to know more?')
st.markdown('We used our own Arctic TROPOMI lightning NO$_2$ data to estimate the **lifetime and production efficiency of lightning NO$_2$**.')
st.markdown('A detailed description of the methodology can be found in our ES&T paper "*Spaceborne observations of lightning NO$_2$ in the Arctic*" (In Review).')
st.markdown('Hope this app could help you understand the importance of lightning NO$_2$ and inspire some new ideas.')

st.image('./imgs/homepage.jpg')